#!/usr/bin/env python3
"""Generate Phase B UVM wrappers and Makefile case lists from bucket docs."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


TB_DIR = Path(__file__).resolve().parents[2]
UVM_DIR = TB_DIR / "uvm"


@dataclass(frozen=True)
class Case:
    case_id: str
    method: str
    iteration: int

    @property
    def bucket(self) -> str:
        return {
            "B": "BASIC",
            "E": "EDGE",
            "P": "PROF",
            "X": "ERROR",
        }[self.case_id[0]]

    @property
    def class_name(self) -> str:
        return f"rdma_cq_pusher_{self.case_id.lower()}_test"


ROW_RE = re.compile(r"^\|\s*([BEPX][0-9]{3})\s*\|\s*([DR])\s*\|.*?\|\s*([0-9]+)\s*\|")


def parse_cases(path: Path) -> list[Case]:
    cases: list[Case] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ROW_RE.match(line)
        if not match:
            continue
        cases.append(Case(match.group(1), match.group(2), int(match.group(3))))
    return cases


def all_cases() -> list[Case]:
    result: list[Case] = []
    for name in ("DV_BASIC.md", "DV_EDGE.md", "DV_PROF.md", "DV_ERROR.md"):
        result.extend(parse_cases(TB_DIR / name))
    result.sort(key=lambda c: ("BEPX".index(c.case_id[0]), int(c.case_id[1:])))
    if len(result) != 512:
        raise SystemExit(f"expected 512 cases, parsed {len(result)}")
    return result


def write_if_changed(path: Path, text: str) -> None:
    if not text.endswith("\n"):
        text += "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != text:
        path.write_text(text, encoding="utf-8")


def render_catalog(cases: list[Case]) -> str:
    out: list[str] = [
        "`ifndef RDMA_CQ_PUSHER_PHASE_B_CATALOG_SV",
        "`define RDMA_CQ_PUSHER_PHASE_B_CATALOG_SV",
        "",
        "function automatic string rdma_cq_pusher_case_bucket(input string cid);",
        "  if (cid.len() == 0) return \"UNKNOWN\";",
        "  if (cid.substr(0, 0) == \"B\") return \"BASIC\";",
        "  if (cid.substr(0, 0) == \"E\") return \"EDGE\";",
        "  if (cid.substr(0, 0) == \"P\") return \"PROF\";",
        "  if (cid.substr(0, 0) == \"X\") return \"ERROR\";",
        "  return \"UNKNOWN\";",
        "endfunction",
        "",
        "function automatic string rdma_cq_pusher_case_method(input string cid);",
    ]
    for case in cases:
        out.append(f"  if (cid == \"{case.case_id}\") return \"{case.method}\";")
    out += [
        "  return \"D\";",
        "endfunction",
        "",
        "function automatic int unsigned rdma_cq_pusher_case_iter(input string cid);",
    ]
    for case in cases:
        out.append(f"  if (cid == \"{case.case_id}\") return {case.iteration};")
    out += [
        "  return 1;",
        "endfunction",
        "",
        "`endif",
    ]
    return "\n".join(out)


def render_tests(cases: list[Case]) -> str:
    out: list[str] = [
        "`ifndef RDMA_CQ_PUSHER_PHASE_B_TESTS_SV",
        "`define RDMA_CQ_PUSHER_PHASE_B_TESTS_SV",
        "",
    ]
    for case in cases:
        out += [
            f"class {case.class_name} extends rdma_cq_pusher_phase_b_case_test;",
            f"  `uvm_component_utils({case.class_name})",
            "",
            "  function new(string name, uvm_component parent);",
            "    super.new(name, parent);",
            "  endfunction",
            "",
            "  function string default_case_id();",
            f"    return \"{case.case_id}\";",
            "  endfunction",
            "endclass",
            "",
        ]
    out.append("`endif")
    return "\n".join(out)


def make_var(name: str, values: list[str]) -> list[str]:
    if not values:
        return [f"{name} :="]
    out = [f"{name} := \\"]
    for idx, value in enumerate(values):
        suffix = " \\" if idx + 1 < len(values) else ""
        out.append(f"  {value}{suffix}")
    return out


def render_makefile(cases: list[Case]) -> str:
    out: list[str] = [
        "# Generated by scripts/generate_phase_b_tests.py; do not hand-edit.",
        "",
    ]
    for bucket in ("BASIC", "EDGE", "PROF", "ERROR"):
        bucket_cases = [c for c in cases if c.bucket == bucket]
        ids = [c.case_id for c in bucket_cases]
        entries = [f"{c.class_name}:{c.case_id}" for c in bucket_cases]
        prefix = bucket
        out.extend(make_var(f"{prefix}_CASE_IDS", ids))
        out.append("")
        out.extend(make_var(f"{prefix}_CASES", entries))
        out.append("")
    out.extend(
        [
            "ALL_CASE_IDS := $(BASIC_CASE_IDS) $(EDGE_CASE_IDS) $(PROF_CASE_IDS) $(ERROR_CASE_IDS)",
            "ALL_CASES := $(BASIC_CASES) $(EDGE_CASES) $(PROF_CASES) $(ERROR_CASES)",
            "ALL_UCDBS := $(addprefix $(TB_DIR)/cov_after/,$(addsuffix .ucdb,$(ALL_CASE_IDS)))",
            "ALL_SCORECARDS := $(addprefix $(TB_DIR)/cov_after/,$(addsuffix .scorecard.json,$(ALL_CASE_IDS)))",
            "BASIC_UCDBS := $(addprefix $(TB_DIR)/cov_after/,$(addsuffix .ucdb,$(BASIC_CASE_IDS)))",
            "EDGE_UCDBS := $(addprefix $(TB_DIR)/cov_after/,$(addsuffix .ucdb,$(EDGE_CASE_IDS)))",
            "PROF_UCDBS := $(addprefix $(TB_DIR)/cov_after/,$(addsuffix .ucdb,$(PROF_CASE_IDS)))",
            "ERROR_UCDBS := $(addprefix $(TB_DIR)/cov_after/,$(addsuffix .ucdb,$(ERROR_CASE_IDS)))",
            "",
        ]
    )
    return "\n".join(out)


def main() -> int:
    cases = all_cases()
    write_if_changed(UVM_DIR / "tests" / "rdma_cq_pusher_phase_b_catalog.sv", render_catalog(cases))
    write_if_changed(UVM_DIR / "tests" / "rdma_cq_pusher_phase_b_tests.sv", render_tests(cases))
    write_if_changed(UVM_DIR / "phase_b_case_map.mk", render_makefile(cases))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
